# Generated by Django 4.1.5 on 2023-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_tab',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField(max_length=10)),
                ('doctor_id', models.IntegerField(max_length=10)),
                ('service_id', models.IntegerField(max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('approve', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'appointment_tab',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='doctor_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(max_length=10)),
                ('notes', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'doctor_availability',
            },
        ),
        migrations.CreateModel(
            name='doctor_change_time',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField(max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor_change_time',
            },
        ),
        migrations.CreateModel(
            name='doctor_tab',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor_tab',
            },
        ),
        migrations.CreateModel(
            name='patient_registration',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('contact_no', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patient_registration',
            },
        ),
        migrations.CreateModel(
            name='service_tab',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service_tab',
            },
        ),
    ]
